/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as PropertiesIdRouteImport } from './routes/properties/$id'
import { Route as PropertiesNewRouteImport } from './routes/properties/new'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as RequestsIdRouteImport } from './routes/requests/$id'
import { Route as RequestsNewRouteImport } from './routes/requests/new'
import { Route as FormTokenIndexRouteImport } from './routes/form/$token/index'
import { Route as FormTokenThanksRouteImport } from './routes/form/$token/thanks'
import { Route as PropertiesIdEditRouteImport } from './routes/properties/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesNewRoute = PropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FormTokenIndexRoute = FormTokenIndexRouteImport.update({
  id: '/form/$token/',
  path: '/form/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormTokenThanksRoute = FormTokenThanksRouteImport.update({
  id: '/form/$token/thanks',
  path: '/form/$token/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdEditRoute = PropertiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PropertiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/new': typeof PropertiesNewRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/properties/': typeof PropertiesIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/form/$token/thanks': typeof FormTokenThanksRoute
  '/properties/$id/edit': typeof PropertiesIdEditRoute
  '/form/$token/': typeof FormTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/new': typeof PropertiesNewRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/properties': typeof PropertiesIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/form/$token/thanks': typeof FormTokenThanksRoute
  '/properties/$id/edit': typeof PropertiesIdEditRoute
  '/form/$token': typeof FormTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/new': typeof PropertiesNewRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/properties/': typeof PropertiesIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/form/$token/thanks': typeof FormTokenThanksRoute
  '/properties/$id/edit': typeof PropertiesIdEditRoute
  '/form/$token/': typeof FormTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/properties/$id'
    | '/properties/new'
    | '/requests/$id'
    | '/requests/new'
    | '/properties/'
    | '/requests/'
    | '/form/$token/thanks'
    | '/properties/$id/edit'
    | '/form/$token/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/properties/$id'
    | '/properties/new'
    | '/requests/$id'
    | '/requests/new'
    | '/properties'
    | '/requests'
    | '/form/$token/thanks'
    | '/properties/$id/edit'
    | '/form/$token'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/settings'
    | '/properties/$id'
    | '/properties/new'
    | '/requests/$id'
    | '/requests/new'
    | '/properties/'
    | '/requests/'
    | '/form/$token/thanks'
    | '/properties/$id/edit'
    | '/form/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  PropertiesIdRoute: typeof PropertiesIdRouteWithChildren
  PropertiesNewRoute: typeof PropertiesNewRoute
  RequestsIdRoute: typeof RequestsIdRoute
  RequestsNewRoute: typeof RequestsNewRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  FormTokenThanksRoute: typeof FormTokenThanksRoute
  FormTokenIndexRoute: typeof FormTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/new': {
      id: '/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof PropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$token/': {
      id: '/form/$token/'
      path: '/form/$token'
      fullPath: '/form/$token/'
      preLoaderRoute: typeof FormTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$token/thanks': {
      id: '/form/$token/thanks'
      path: '/form/$token/thanks'
      fullPath: '/form/$token/thanks'
      preLoaderRoute: typeof FormTokenThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id/edit': {
      id: '/properties/$id/edit'
      path: '/edit'
      fullPath: '/properties/$id/edit'
      preLoaderRoute: typeof PropertiesIdEditRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
  }
}

interface PropertiesIdRouteChildren {
  PropertiesIdEditRoute: typeof PropertiesIdEditRoute
}

const PropertiesIdRouteChildren: PropertiesIdRouteChildren = {
  PropertiesIdEditRoute: PropertiesIdEditRoute,
}

const PropertiesIdRouteWithChildren = PropertiesIdRoute._addFileChildren(
  PropertiesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  PropertiesIdRoute: PropertiesIdRouteWithChildren,
  PropertiesNewRoute: PropertiesNewRoute,
  RequestsIdRoute: RequestsIdRoute,
  RequestsNewRoute: RequestsNewRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  FormTokenThanksRoute: FormTokenThanksRoute,
  FormTokenIndexRoute: FormTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
